version: '3'
services:
  app:
    image: node:latest
    working_dir: /app
    container_name: todo-react
    volumes:
      - .:/app
    ports:
      - 1234:1234
      - 1235:1235
    environment:
      - CHOKIDAR_USEPOLLING=1
